import fs from "fs";
import path from "path";
import { ApolloServer } from "apollo-server";
import neo4j from "neo4j-driver";
import { neo4jgraphql, makeAugmentedSchema } from "neo4j-graphql-js";
import bcrypt from 'bcrypt'

/*
* Create an executable GraphQL schema object from GraphQL type definitions
* including autogenerated queries and mutations.
* Optionally a config object can be included to specify which types to include
* in generated queries and/or mutations. Read more in the docs:
* https://grandstack.io/docs/neo4j-graphql-js-api.html#makeaugmentedschemaoptions-graphqlschema
*/
const schemaFilePath = path.join(__dirname, "schema.graphql");
const schema = makeAugmentedSchema({
	typeDefs: fs.readFileSync(schemaFilePath).toString("utf-8"),
	config: {
		// auth: {
		// 	hasRole: true,
		// 	isAuthenticated: true
		// }
	},
	resolvers: {
		Mutation: {
			CreateUser: (object, params, ctx, resolveInfo) => {
				params.password = bcrypt.hashSync(params.password, 10)
				// @TODO: sign a token and return with response
				return neo4jgraphql(object, params, ctx, resolveInfo);
			},
			LoginUser: async (object, params, ctx, resolveInfo) => {
				const result = await neo4jgraphql(object, params, ctx, resolveInfo);
				const passwordIsCorrect = bcrypt.compareSync(params.password, result.properties.password)
				// @TODO: sign a token and return with response
				// @TODO: throw an error for incorrect credentials
				return passwordIsCorrect
			}
		}
	}
});

/*
 * Create a Neo4j driver instance to connect to the database
 * using credentials specified as environment variables
 * with fallback to defaults
 */
const driver = neo4j.driver(
	"bolt://localhost:7687",
	neo4j.auth.basic("neo4j", "parola")
);

/*
 * Create a new ApolloServer instance, serving the GraphQL schema
 * created using makeAugmentedSchema above and injecting the Neo4j driver
 * instance into the context object so it is available in the
 * generated resolvers to connect to the database.
 */
const server = new ApolloServer({
	context: ({ req, res }) => {
		return {
			driver,
			req,
			// cypherParams: {
			// 	currentUserId: req.user.id
			// }
		};
	},
	schema
});

server.listen(4000).then(({ url }) => {
	console.log(`GraphQL API ready at ${url}`);
});
